kiagnose/kiagnose

- .github/workflows/check.yaml
- automation/make.sh
- go.mod
- kiagnose/mainflow.go
- kiagnose/mainflow_test.go
Introducing the project skeleton, including a placeholder for the library entry-point, the script to run the tests and CI to run them on every PR.
> kiagnose: Introduce basic skeleton

- .github/workflows/check.yaml
- .golangci.yml
- automation/make.sh
- kiagnose/mainflow.go
- kiagnose/mainflow_test.go
The golangci linter [1] will perform a static analisys
on the code.
Developers can run it locally using:
`./automation/make.sh --lint`
The CI will run it as a check.
Note: Existing formatting issues have been fixed in this PR.
[1] https://github.com/golangci/golangci-lint
~Depends on #1~
> linter: Introduce the golangci linter

- automation/make.sh
`make.sh --lint` option was missing.
> make.sh: Add lint long option

- automation/make.sh
This PR adds the `--build-core` option to `make.sh --help`.
Furthermore it changes `BINARY_NAME` variable name to `CORE_BINARY_NAME` in order to differentiate the core binary from future checkups binaries.
> make.sh: Minor changes

- automation/make.sh
- dockerfiles/Dockerfile.kiagnose
This adds a Dockerfile and a simple build system for the image:
```bash
./automation/make.sh --build-core-image
```
It supports podman as a default, with the ability to choose arbitrary CRIs such as Docker:
```bash
CRI=docker ./automation/make.sh --build-core-image
```
An image tag can also be set:
```bash
CORE_IMAGE_TAG=0.1.0 ./automation/make.sh --build-core-image
```
~~This PR depends on PR #21.~~
> image: Build an image from cmd

- kiagnose/cmd/environment.go
- kiagnose/cmd/main.go
Since main() and envToMap() are both in the "main" package,
there is no need for envToMap() to be exported.
> main: Unexport envToMap()

- .github/workflows/publish.yaml
- automation/make.sh
After a PR is merge the kiagnose core image has to be pushed so users
can consume it. This change push the core kiagnose image on PR merges at
quay.io/kiagnose/kiagnose:main.
Notes for reviewers:
This cannot be tested on the PR since secrets are not passed to jobs running at PRs.
Tested with [act](https://github.com/nektos/act)
> actions, publish: Push the main core image

- .github/workflows/checkup-kubevirt-vm-latency.yaml
- checkups/kubevirt-vm-latency/Dockerfile
- checkups/kubevirt-vm-latency/automation/make.sh
- checkups/kubevirt-vm-latency/cmd/main.go
- checkups/kubevirt-vm-latency/go.mod
Add the kubevirt VM latency checkup skeleton as a submodule.
It includes:
- Placeholder main().
- Automation scripts (`make.sh`) to linter, unit test, build and create
a container image.
- Dockerfile.
Note that the scripts on the submode should be executed under
`checkups/kubevirt-vm-latency`.
> checkups: Introduce kubevirt-vm-latency skeleton

- .github/workflows/check.yaml
- automation/make.sh
- checkups/echo/Dockerfile
- checkups/echo/README.md
- checkups/echo/entrypoint
- checkups/echo/entrypoint_test
- checkups/echo/fake_kubectl
- checkups/echo/manifests/dev/echo-checkup.yaml
This adds a basic checkup that shall be used as:
1. A debugging tool for developing the project.
2. A reference to create more advanced and useful checkups.
The checkup basically receives a string as an input, and writes it without modification to it's output.
This adds an option to make.sh to unit test the checkup's entrypoint script:
```bash
./automation/make.sh --echo-unit-test
```
This adds an option to make.sh to build the checkup's image:
```bash
./automation/make.sh --echo-build-image
```
It supports podman as a default, with the ability to choose arbitrary container engines such as Docker:
```bash
CRI=docker ./automation/make.sh --echo-build-image
```
An image tag can also be set:
```bash
ECHO_IMAGE_TAG=0.1.0 ./automation/make.sh --echo-build-image
```
Signed-off-by: Orel Misan …
> Add echo checkup

- .github/workflows/checkup-kubevirt-vm-latency.check.yaml
- .github/workflows/checkup-kubevirt-vm-latency.publish.yaml
- checkups/kubevirt-vm-latency/automation/make.sh
This check has it's own directory so the github actions use it as
workdir also the other actions has being moved to files with similar
names.
Signed-off-by: Enrique Llorente <ellorent@redhat.com>
> automation: Push kubevirt-vm-latency image

- kiagnose/internal/checkup/checkup.go
- kiagnose/internal/checkup/checkup_test.go
- kiagnose/internal/checkup/job/job.go
This PR introduce the logic for actually executing a checkup in a cluster.
With this PR changes the framework will create a batch Job to run the checkup image
and waits for it to finish.
A Job is considered as finished when its status has 'Completed' or 'Failed' condition.
> Start and wait for a checkup Job to finish

- manifests/kiagnose.yaml
This adds the required K8s objects for the framework to work:
Namespace, ServiceAccount, ClusterRole and ClusterRoleBinding.
To install the framework:
```bash
$ kubectl apply -f manifests/kiagnose.yaml
```
To remove the framework:
```bash
$ kubectl delete -f manifests/kiagnose.yaml
```
> manifests: Add installation manifest

- .github/workflows/check.yaml
- automation/make.sh
Optimize and fix lint issues:
- Run root lint on the `kiagnose` and `cmd` folders (excluse `checkups`).
- Bump lint version.
- Add verbosity to the run (to see where is time consumed).
- Increase timeout (as the current one started failing).
> automation/CI: Exclude linting checkups, bump lint version, add verbosity and increase timeout

- kiagnose/internal/config/config.go
- kiagnose/internal/configmap/configmap.go
This PR changes `configmap.GetData()` to `configmap.Get()` which returns the full ConfigMap object instead of just its Data field.
Another minor change is changing the client type to `CoreV1Interface` in order to match `configmap.Create()` signature.
> configmap: Change GetData() to Get()

- automation/make.sh
- checkups/kubevirt-vm-latency/automation/make.sh
The current default handling in the automation scripts are not scalable.
Each time a new argument is added, there is a need to also add it
to the default handling condition.
With this change, instead of checking if each specific argument is not
set, a global check is done against the number of arguments the script
is called with. If no arguments are provided, the default options are
triggered.
> *_Note_*: Depends on #38
> automation: Use defaults when no args are provided

- checkups/echo/manifests/echo-checkup.yaml
This adds a manifest to configure and run the echo-checkup.
Note: The following instructions assume the framework is installed.
To run the echo checkup:
```bash
$ kubectl apply -f checkups/echo/manifests/echo-checkup.yaml
```
To view the results:
```bash
$ kubectl get configmap echo-checkup-example-config -n kiagnose -o yaml
```
To delete all objects created by this manifest:
```bash
$ kubectl delete -f checkups/echo/manifests/echo-checkup.yaml
```
This PR depends on PR #36.
> echo-checkup: Add production manifest

- kiagnose/internal/configmap/configmap.go
- kiagnose/internal/launcher/launcher.go
- kiagnose/internal/launcher/launcher_test.go
- kiagnose/internal/reporter/reporter.go
- kiagnose/internal/reporter/reporter_test.go
- kiagnose/internal/status/status.go
- kiagnose/mainflow.go
This PR adds basic reporting capability:
1. The `startTimestamp` and `completionTimestamp` are recorded and reported.
2. `succeeded` field is always reported as `false`.
3. `failureReason` field is always reported as `Failure: implement me`.
> reporter: Add basic reporting capability

- kiagnose/internal/checkup/checkup.go
- kiagnose/internal/launcher/launcher.go
- kiagnose/internal/launcher/launcher_test.go
Replace the hard codded report of "succeeded" and "failureReason" with an actual report.
The "succeeded" field is reported as "true" only when:
Checkup.Setup(), Checkup.Run() and Checkup.Teardown() are successfully completed.
At the moment, because the checkup results are not read, beyond the returned error from Checkup.Run(), there is not enough
data to declare the checkup as failed.
This PR also changes the launcher's tests to test the actual final report (in applicable test cases).
~~Depends on PR #45.~~
> launcher: Report actual checkup status

- kiagnose/internal/checkup/checkup.go
- kiagnose/internal/launcher/launcher.go
- kiagnose/internal/launcher/launcher_test.go
- kiagnose/internal/reporter/reporter.go
- kiagnose/internal/reporter/reporter_test.go
- kiagnose/internal/results/results.go
- kiagnose/internal/results/results_test.go
- kiagnose/internal/status/status.go
Until now, the results reported by the checkup hasn't been read by the framework.
Read and report the checkup's reported results:
1. `succeeded`.
2. `failureReason`.
3. Checkup custom results (optional).
The "succeeded" field value is a "true", when no errors had occurred in the framework or in the checkup.
The `failureReason` field is a concatenation of:
1. The value reported by the checkup (if exists).
2. `Checkup.Run()` error (if occurred).
3. `Checkup.Results()` error (if occurred).
4. `Checkup.Teardown()` error (if occurred).
~~Depends on PR #46.~~
> reporter: Report checkup results

- .golangci.yml
The hugeParam linter warns against passing a large amount of data to a
function, causing a large copy.
The cost of a copy is not always obvious.
There are several reasons against converting data to a pointer:
- Readability: From the caller stand of view, passing a pointer may be
interpreted as if the function is going to mutate the data.
- The compiler may optimize the machine code such that there is no copy.
- Passing a pointer may imply usage of the heap, which is also costly
(compare to the stack).
Increasing the threshold value higher, gives more control to
the code author to decide what fits as a pointer and what not.
> linter: Increase hugeParam threshold size (to 1024)

- kiagnose/internal/launcher/launcher.go
- kiagnose/internal/launcher/launcher_test.go
- kiagnose/internal/reporter/reporter.go
- kiagnose/internal/reporter/reporter_test.go
When function receivers or arguments are defined as pointers, beyond the
functional need it also exposes an intent.
When reading the code, an expression like `foo(&myvar)` has the
potential to be interpreted as: "foo is mutating myvar".
On the other hand, seeing `foo(myvar)` is more likely to express to the
reader that the intent is to keep the variable immutable.
The PR reverts the move to pointers due to a linter requirement [1].
[1] https://github.com/kiagnose/kiagnose/pull/48
~Depends on #51 (for this one to pass the checks).~
> Do not use pointers when not needed

- .github/workflows/checkup-kubevirt-vm-latency.check.yaml
- checkups/kubevirt-vm-latency/automation/make.sh
The timeout is increased due to the expected codebase size.
The scanned folders are now explicitly specified.
The linter configuration is now in sync with the one from kiagnose core.
> CI, checkup/vm-latency: Update linter version and args

- .github/workflows/check.yaml
- .gitignore
- automation/e2e.sh
- automation/make.sh
A dedicated e2e test target has been added to the `make.sh` script.
It delegates all arguments to the new `e2e.sh` script which assists in
deploying a cluster (using `kind`) and `kiagnose`.
The new e2e script also includes a basic sanity validation that deploys
and runs the `echo` checkup.
To run the full set of e2e targets, run:
```
./automation/make.sh --e2e -- \
--install-kind \
--install-kubectl \
--create-cluster \
--deploy-kiagnose \
--run-tests \
--delete-cluster`
```
This PR also includes running the same on CI.
Notes:
- This is a minimalist e2e test validation which should be used as a basic sanity check, assuring the success path for kiagnose.
It is a temporary step until an e2e test suite is introduced.
- The current (explicit) polling could have been improved by using `kubectl …
> automation, CI: Introduce basic e2e test infrastructure

- automation/e2e.sh
The default binaries used in the e2e (sanity) tests (`kind` and
`kubectl`) have been set with a relative path (`./`).
This does not work well when running locally.
To solve this, an explicit full path is used instead.
> automation, e2e: Set default binaries with full path

- checkups/kubevirt-vm-latency/cmd/environment.go
- checkups/kubevirt-vm-latency/cmd/main.go
- checkups/kubevirt-vm-latency/go.mod
- checkups/kubevirt-vm-latency/manifests/clusterroles.yaml
- checkups/kubevirt-vm-latency/manifests/dev/kubevirt-vm-latency-checkup.yaml
- checkups/kubevirt-vm-latency/manifests/kubevirt-vm-latency-checkup.yaml
- checkups/kubevirt-vm-latency/manifests/sriov-network-attachment-definition.yaml
- checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
- checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup_test.go
- checkups/kubevirt-vm-latency/vmlatency/internal/client/client.go
- checkups/kubevirt-vm-latency/vmlatency/internal/launcher/launcher.go
- checkups/kubevirt-vm-latency/vmlatency/internal/launcher/launcher_test.go
- checkups/kubevirt-vm-latency/vmlatency/internal/vmi/cloudinit.go
- checkups/kubevirt-vm-latency/vmlatency/internal/vmi/operation.go
- checkups/kubevirt-vm-latency/vmlatency/internal/vmi/spec.go
- checkups/kubevirt-vm-latency/vmlatency/mainflow.go
With this PR changes the Kubevirt VM lantecy checkup will spin up two SR-IOV VMs inside its working namespace.
Each VM is configured with custom MAC address and static IP address using cloudinit.
On teadown, is will do best effort to delete the VMs, in case a once of the VMs fail to delete 
or did was not disposed on time it wont fail immediately. 
Instead it will try delete next VM, when finished it will return an error with the failing VMs and errors.
In order to deploy the checkup, apply the manifests under 'checkups/kubevirt-vm-latency/manifests':
from checkups/kubevirt-vm-latency:
```
$ kubectl apply -f ./manifests/sriov-network-attachment-definition.yaml
$ kubectl apply -f ./manifests/clusterroles.yaml
$ kubectl apply -f ./manifests/kubevirt-vm-latency-checkup.yaml
```
View results: …
> kubevirt-vm-latency: Spin up VMs 

- checkups/kubevirt-vm-latency/automation/e2e.sh
- checkups/kubevirt-vm-latency/automation/make.sh
Introduce scripts to support e2e test infrastructure for the
kubevirt-vm-latency checkup.
The script currently includes targets to install `kind` and `kubectl`,
deploy `kiagnose` and `kubevirt`.
To run all targets, you can execute the following command:
`./checkups/kubevirt-vm-latency/automation/make.sh --e2e`
> checkup-vm-latency, automation: Introduce e2e test deploy helpers

- checkups/kubevirt-vm-latency/vmlatency/internal/vmi/spec.go
A VM considred ready when AgentConnected condition is met,
meaning that the VM had booted and QEMU Guest Agent (GA) is running.
It seems that the GA wont start on alpine image causing the checkup to
always with VM not read error.
> kubevirt-vm-latency: Use fedora image

- checkups/kubevirt-vm-latency/vmlatency/internal/vmi/spec.go
In order to ensure a VM is scheduled on specific node, the VM node
selector is set with "kubernetes.io/hostname" label.
Setting this label with an empty string (i.e: kubernetes.io/hostname="")
cause the VMs to stuck on 'Scheduling' phase as it looks for a node
that does not exists.
It seems that the value of "kubernetes.io/hostname" label is no validated.
> kubevirt-vm-latency: Do not set node-selector when node name is empty

- checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
- checkups/kubevirt-vm-latency/vmlatency/internal/vmi/spec.go
This PR is a follow up to PR #70 - the OS image was switched from Alpine to Fedora.
Reflect this change in the name of the function that creates this VMI.
> latency, vmi, spec: Rename NewAlpine() to NewFedora()

- checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
This PR fixes the checkup setup to wait for both source and target VMs until they are ready.
> kubevirt-vm-latency, setup: Wait for source and target VMs until ready

- checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
- checkups/kubevirt-vm-latency/vmlatency/internal/vmi/operation.go
With this PR changes the VMs latest state is fetched when they are ready.
Once the VMs are ready their state includes crucial info that will be used by the checkup (i.e: namespace, status..)
> kubevirt-vm-latency ,setup: Fetch VMs latest state when they are ready

- .github/workflows/check.yaml
- .github/workflows/checkup-kubevirt-vm-latency.check.yaml
- automation/e2e.sh
- checkups/kubevirt-vm-latency/automation/e2e.sh
The following targets where performed from the latency checkup's `e2e.sh` file:
```
--install-kind
--install-kubectl
--create-cluster
--deploy-kiagnose
```
These targets are general to all checkups, so they were moved to the main `e2e.sh` file.
The `--delete-cluster` target in the checkup's `e2e.sh` script was redundant, because it is also present at the main `e2e.sh` script.
> latency, CI, e2e: Move general targets to main e2e.sh

- kiagnose/internal/checkup/job/job.go
Events received about the checkup job are currently logged by kiagnose,
but there seem to be no useful reason for such a debug level logging.
(it may be worth the effort once issues are found in this area and a
proper logging library is used to support setting levels of logs)
> checkup, job: Remove redundant event log

- .github/workflows/checkup-kubevirt-vm-latency.check.yaml
- checkups/kubevirt-vm-latency/automation/e2e.sh
Add a flag to control the usage of kubevirt's emulation
feature.
Using this flag, makes the e2e tests to run slower, thus it is disabled
by default.
It is enabled in the CI environment.
> latency, e2e: Add KUBEVIRT_USE_EMULATION environment variable

- kiagnose/internal/checkup/checkup.go
- kiagnose/internal/config/config.go
- kiagnose/internal/configmap/configmap.go
- kiagnose/internal/launcher/launcher_test.go
- kiagnose/internal/reporter/reporter.go
- kiagnose/internal/reporter/reporter_test.go
- kiagnose/internal/results/results.go
- kiagnose/internal/results/results_test.go
Until now, Checkup held as a state, a custom "client" interface which was a small subset of the default "kubernetes.Interface"
client set.
The custom client interface was set up because we didn't know in advanced if K8s fake client will be suitable for our needs.
The custom client interface was forcing its users to use a specific client version (for example CoreV1) instead of having
a choice to select a client from the default client set.
This had a system-wide affect, affecting all functions that were called from Checkup, and using the client.
Because the "configmap" package was affected, other packages were affected as well.
Holding a client from type "kubernetes.Interface", allows its users a choice to select the most suitable client.
> configmap: Use default K8s clientset

- checkups/kubevirt-vm-latency/automation/e2e.sh
Currently `e2e.sh` script is not consistent since there are places where `${KUBECTL}` variable is not being used.
And also there are places where `kubectl create ..` is being used and some `kubectl apply ..`.
This PR align's kubevirt-vm-latency change `automation/e2e.sh` script to use `kubectl apply` verb and the `${KUBECTL}` variable.
Executing `kubectl apply` wont fail if the same object is already exists, which makes it easier to iterate on local 
dev environment (i.e: `e2e.sh` wont fail if Kubevirt already deployed).
> kubevirt-vm-latency: Align automation/e2e.sh script

- kiagnose/internal/checkup/checkup.go
- kiagnose/internal/checkup/job/job.go
Change the client type to default client-set (kubernetes.Interface) in functions belonging to the checkup.job package.
Because we are using K8s fake client as a stub, there is no need to use a client other than the default.
~~Depends on PR #54.~~
> checkup, job: Use default K8s client-set

- kiagnose/internal/checkup/checkup.go
- kiagnose/internal/checkup/serviceaccount/serviceaccount.go
Change the client type of `serviceaccount.Create()` to the default client-set (kubernetes.Interface).
Because we are using K8s fake client as a stub, there is no need to use a client other than the default.
~~Depends on PR #54.~~
> checkup, ServiceAccount: Use default K8s client-set

- automation/make.sh
- checkups/kubevirt-vm-latency/automation/make.sh
To ensure that the vendor directory is in sync with the go.mod this
change enforece the "-mod=vendor" go flag to use the vendor at build and
also for running tests.
> automation: Compile and test with vendor directory

- kiagnose/internal/config/cmparser.go
- kiagnose/internal/config/config_test.go
Currently, if the kubelet cannot pull the required image - we wait for the required timeout before failing.
Add a check if the image field exists but empty, in order to not wait in vain for timeout expiration.
> config: Add a check if checkup image field is empty

- kiagnose/internal/config/cmparser.go
- kiagnose/internal/config/config_test.go
Until this commit, it was possible to receive an empty string as a valid custom parameter name.
Add a check if a custom parameter name is empty, and fail if it is.
> config: Add a check if custom param name is empty

- checkups/kubevirt-vm-latency/automation/e2e.sh
- checkups/kubevirt-vm-latency/go.mod
- checkups/kubevirt-vm-latency/manifests/clusterroles.yaml
- checkups/kubevirt-vm-latency/manifests/kubevirt-vm-latency-checkup.yaml
- checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
- checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup_test.go
- checkups/kubevirt-vm-latency/vmlatency/internal/client/client.go
- checkups/kubevirt-vm-latency/vmlatency/internal/launcher/launcher_test.go
- checkups/kubevirt-vm-latency/vmlatency/internal/vmi/operation.go
Currently the `NetworkAttachmentDefinition` (NAD) namespace and name are passed
to the checkup, w/o verifying it is exists.
In case the NAD does not exists, the checkup will hang until the timeout, because Kubevirt does
not validate that the NAD exists ending up with VMs that wont schedule.
With this PR changes the checkup will verify that before starting the checkup setup,
if the NAD does not exist it will fail early and wont hang until the timeout.
The checkup ClusterRoles manifest is updated with the required permissions to fetch the NAD.
Note that `go.mod` file is updated, but no new dependencies were added.
> vmlatency, checkup, preflight: Verify NetworkAttachmentDefinition exists

- .github/workflows/checkup-kubevirt-vm-latency.check.yaml
- checkups/kubevirt-vm-latency/automation/e2e.sh
Following https://github.com/kiagnose/kiagnose/pull/96
Currently kubevirt-vm-latency checkup e2e test fails consistently due to connectivity issues between the VMs.
It seems that on CI environment traffic between bridge ports is blocked causing e2e test to fail 
due to no communication between VMs over the bridge network.
It seems that setting `sysctl -w net.bridge.bridge-nf-call-iptables=0` or adding iptables rule [[1]](https://github.com/kubevirt/cluster-network-addons-operator#configure-bridge-on-node) 
in order to enable traffic between bridge ports doesn't work on Github Workflow environment.
While troubleshooting, it seems that unloading `br_netfilter` removed the restrictions on traffic between bridge 
ports and made the test pass.
Unloading `br_netfilter` kernel module, ensures …
> vmlatency, automation, e2e: Allow traffic between bridge ports on CI

- kiagnose/internal/checkup/checkup_test.go
Currently, TestCheckupTeardownShould() length is almost at the 100 lines limit (which the linter
enforces).
In order to make room for future changes to this function, the success scenario was split to a different function.
> checkup, tests: Split TestCheckupTeardownShould()

- kiagnose/internal/checkup/checkup.go
- kiagnose/internal/checkup/checkup_test.go
- kiagnose/internal/checkup/namegenerator/namegenerator.go
- kiagnose/mainflow.go
- vendor/k8s.io/apimachinery/pkg/util/rand/rand.go
- vendor/modules.txt
In order to run multiple checkups simultaneously, it is required to run them in Namespaces with a unique name.
Create checkup namespaces with names in the following format:
`kiagnose-checkup-<random string>`
Partially fixes issue #17:
This PR does not handle name randomization of ClusterRoleBindings, which is also required to run multiple checkups simultaneously. It will be done in a follow-up PR.
~~Depends on PR #101.~~
> checkup: Randomize Namespace's name

- checkups/kubevirt-vm-latency/automation/e2e.sh
Currently kubevirt deployment timeout is set to 2 minutes. This
sometimes fail when running locally.
This PR is aligning the timeout to 5m which is the same as kubevirt repo's own deploy
complete [wait](https://github.com/kubevirt/kubevirt/blob/main/hack/cluster-deploy.sh#L128
).
> vm-latency, e2e: Increase deploy kubevirt timeout

- kiagnose/internal/checkup/checkup.go
- kiagnose/internal/checkup/checkup_test.go
In order to run multiple checkups simultaneously, it is required to randomize the ClusterRoleBinding names, which are non-namespaced objects.
Randomize the names of ClusterRoleBinding objects connecting the user-supplied ClusterRoles with the checkup's ServiceAccount object.
ClusterRoleBinding name format:
`<ClusterRole name>-<random string>`
Fixes issue #17.
~~Depends on PR #89.~~
> checkup: Randomize ClusterRoleBindings names

- kiagnose/internal/checkup/checkup_test.go
Currently, assertClusterRoleBindingsCreated() is checking if the expected ClusterRoleBinding objects are a subset of the actual objects.
Change the assertion to `Equal()`, because the expected objects should match the actual ones.
> checkup, tests: Fix assertClusterRoleBindingsCreated()

- checkups/kubevirt-vm-latency/automation/e2e.sh
E2E check on CI sometimes fail due to timeout when waiting for CNAO to be ready.
> Kubevirt VM latnecy, e2e: Increase CNAO ready timeout

- docs/checkup_api.md
Add a document to describe the API between the kiagnose framework
and the checkup.
> documentation: Add checkup API document

- checkups/echo/README.md
Adds usage instructions:
- Prerequisites
- Installation
- Configuration
- Execution
- Results Retrieval
> echo, README: Add usage instructions

- checkups/echo/README.md
Remove dollar sign `$` from bash snippets in order to enable quick copy-paste operations using triple mouse clicks.
> echo, README: Remove $ sign from bash snippets

- checkups/echo/Dockerfile
- checkups/kubevirt-vm-latency/Dockerfile
- dockerfiles/Dockerfile.kiagnose
Bump base image of:
1. Kiagnose
2. Echo checkup
3. VM Latency checkup
to version `8.6-751.1655117800`.
> Bump base image version

- checkups/kubevirt-vm-latency/go.mod
- checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
- checkups/kubevirt-vm-latency/vmlatency/internal/console/console.go
- checkups/kubevirt-vm-latency/vmlatency/internal/latency/latency.go
- checkups/kubevirt-vm-latency/vmlatency/internal/latency/pingparser.go
- checkups/kubevirt-vm-latency/vmlatency/internal/latency/pingparser_test.go
- checkups/kubevirt-vm-latency/vmlatency/internal/vmi/spec.go
Currently, the checkup VMs image is Fedora-based container disk `quay.io/kubevirt/fedora-with-test-tooling-container-disk`.
Alpine image is much lighter than a similar fedora image, it boots faster and requires less resources.
This PR also changes the checkup to use Alpine image.
Since Alpine includes `BusyBox` `ping` implementation which generates a slightly different output the `iputils` version,
the ping parser code is changed accordingly.
That there is an effort to refactor the ping parser code at https://github.com/kiagnose/kiagnose/pull/116.
Note about the VM image tag, since Kubevirt is not released with [[2]](https://github.com/kubevirt/kubevirt/pull/7783) changes yet `quay.io/kubevirtci/alpine-with-test-tooling-container-disk` tag is used.
Signed-off-by: Or Mergi …
> Kubevirt VM latency checkup: Use alpine image for VMs

- .github/workflows/checkup-echo.publish.yaml
- .github/workflows/checkup-kubevirt-vm-latency.publish.yaml
- .github/workflows/publish.yaml
When repository is tagged with a semver it need to also tag the
generated containers at quay.io, this changes add a new trigger to push
containers and use the trigger ref to tag the container.
Signed-off-by: Enrique Llorente <ellorent@redhat.com>
> actions: Push tags to quay.io

- checkups/echo/README.md
Replace the deprecated [1] `serviceAccount` field to `serviceAccountName`.
[1] https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#deprecated
> echo, README: Replace serviceAccount to serviceAccountName

- checkups/kubevirt-vm-latency/automation/e2e.sh
Occasionally, the latency measured on Github Actions is greater
than the defined threshold, which causes the e2e test to fail.
Increase the max latency by a factor of 5.
> vm latency, e2e: Increase max latency threshold

- kiagnose/internal/checkup/checkup.go
- kiagnose/internal/checkup/checkup_test.go
- kiagnose/mainflow.go
Currently, the results ConfigMap object's name is constant.
As a preliminary step to checkup execution in a target namespace,
name the results ConfigMap with the following format:
`<user-supplied-CM-name>-results`
> checkup: Name results CM after user-supplied CM

- kiagnose/internal/checkup/checkup.go
- kiagnose/internal/checkup/checkup_test.go
Currently, the results ConfigMap writer Role object's name is constant.
As a preliminary step to checkup execution in a target namespace,
name the results ConfigMap writer Role with the following format:
`<user-supplied-CM-name>-results-cm-writer`
~~Depends on PR #127.~~
> checkup: Name CM-writer Role after user-supplied CM

- kiagnose/internal/checkup/checkup.go
- kiagnose/internal/checkup/checkup_test.go
Currently, the checkup Job object's name is constant.
As a preliminary step to checkup execution in a target namespace,
name the checkup Job with the following format:
`<user-supplied-CM-name>`
~~Depends on PR #129.~~
> checkup: Name checkup Job after user-supplied CM

- kiagnose/internal/checkup/checkup.go
- kiagnose/internal/checkup/checkup_test.go
In order to be aligned with the rest of the code,
the namespace name parameter should be first and the object name second.
~~This PR depends on PR #133.~~
> checkup: Align functions to receive namespace first and name second

- kiagnose/internal/checkup/checkup.go
- kiagnose/internal/checkup/checkup_test.go
Currently, there is a serviceAccountSubject used for creating RoleBinding objects.
Use it to create ClusterRoleBinding objects as well.
This PR depends on PR #134.
> checkup: Use Subject to create ClusterRoleBindings

- kiagnose/internal/checkup/checkup.go
- kiagnose/internal/checkup/checkup_test.go
Currently, the `NamespaceName` constant is used as a prefix to the ephemeral namespace's name.
Rename `NamespaceName` to `EphemeralNamespacePrefix` in order to make its function clearer.
> checkup: Rename checkup.NamespaceName constant

- kiagnose/internal/checkup/checkup_test.go
Currently, related subtests are not sharing a common setup.
Use shared setup in order to emphasise the commonality between subtests - initialize common `testClient` and `nameGeneratorStub` in one place.
> checkup, tests: Use shared setup

- automation/e2e.sh
The echo checkup test case uses kubectl with yaml manifests received from stdin.
Because no files are being used from the checkup's directory - there is no need to change directories.
> e2e: Remove redundant cd directives

- kiagnose/internal/rbac/rbac.go
Currenly, there is a variable name in CreateRoles() with the same name as createRole().
Rename `createRole` variable to `createdRole`.
> rbac: Fix name shadowing

- kiagnose/internal/checkup/checkup_test.go
Currently, in a test checking failure to delete a namespace
object, we expect an error regarding ClusterRoleBinding.
Fix the expected error to refer to a namespace object.
> checkup, tests: Fix wrong expected error

- README.md
- checkups/echo/README.md
- checkups/kubevirt-vm-latency/README.md
- checkups/kubevirt-vm-latency/automation/e2e.sh
- kiagnose/internal/checkup/checkup.go
- kiagnose/internal/checkup/checkup_test.go
- kiagnose/internal/checkup/job/job.go
- kiagnose/internal/checkup/serviceaccount/serviceaccount.go
- kiagnose/internal/configmap/configmap.go
- kiagnose/internal/rbac/rbac.go
- kiagnose/mainflow.go
- manifests/kiagnose.yaml
Currently, checkups are executed in ephemeral Namespace objects.
This change enables checkup execution in a target Namespace - the Namespace in which the user-supplied ConfigMap object is at.
Create and delete an ephemeral namespace only if the user-supplied ConfigMap object is at the "kiagnose" namespace.
Else, setup all objects in the target Namespace.
This PR implements the design document published in PR #126.
Followup PRs will:
1. Split checkup_test.go to test cases regarding ephemeral and target namespace scenarios.
2. Add failure test cases for the target namespace feature.
~~This PR depends on PR #140.~~
> checkup: Introduce target Namespace

- .github/workflows/check.yaml
- .github/workflows/checkup-echo.check.yaml
- automation/e2e.sh
- checkups/echo/automation/e2e.sh
- checkups/echo/automation/make.sh
Currently, Kiagnose e2e test is a success scenario with the echo checkup.
Move this e2e test to be under the "echo.checks" workflow in order to be aligned with the VM latency checkup workflow.
Furthermore, the echo e2e test is using kiagnose and echo-checkup images pulled from quay and not locally built images
from current source code.
Move the echo e2e test code from `automation/e2e.sh` to `checkups/echo/automation/e2e.sh`.
Use locally built images of kiagnose and echo-checkup.
Align the e2e job with the e2e job of vm latency checkup.
Use target namespace instead of ephemeral namespace in the e2e test.
> CI: Fix echo checkup e2e tests to use locally built images

- .gitignore
- automation/e2e.sh
- checkups/kubevirt-vm-latency/automation/e2e.sh
This change is required to support testing network connectivity
across cluster nodes over linux-bridge.
Currently KinD does not support secondary networks for cluster nodes.
Each worker node is connected through veth pair to establish connectivity.
Next each node veth is connected to its own bridge that the cluster workloads will consume through NetworkAttachmentDefinition.
Notes:
- This change introduces using koko [[1]](https://github.com/redhat-nfvpe/koko) utility, it enables connecting between containers network namespaces in a convenient way.
- Connecting between container network namespaces requires high privileges.
- There is an emerging project that enables spinning up KinD cluster with secondary networks [[2]](https://github.com/aojea/kind-networking-plugins/tree/main/baremetal) …
> e2e infra: Support multi nodes cluster

- checkups/kubevirt-vm-latency/vmlatency/internal/client/client.go
Perform two small fixes on `client.UpdateConfigMap()`:
1. Fix a typo in parameter name: `date` -> `data`.
2. Fix a variable shadowing.
> vm latency, client: Fix UpdateConfigMap()

- .github/workflows/checkup-echo.check.yaml
This is a follow-up to PR #162.
Currently, the echo checkup's e2e tests are using `kind` and `kubectl` supplied by the runner-image [1].
Use the `kind` and `kubectl` versions stated at automation/e2e.sh.
[1] https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#tools
> github actions, echo e2e: Use custom kind and kubectl versions

- .github/workflows/checkup-kubevirt-vm-latency.check.yaml
- checkups/kubevirt-vm-latency/README.md
- checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
- checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup_test.go
- checkups/kubevirt-vm-latency/vmlatency/internal/config/config.go
- checkups/kubevirt-vm-latency/vmlatency/internal/config/config_test.go
- checkups/kubevirt-vm-latency/vmlatency/internal/launcher/launcher_test.go
- checkups/kubevirt-vm-latency/vmlatency/internal/vmi/affinity.go
- checkups/kubevirt-vm-latency/vmlatency/internal/vmi/spec.go
Currently, when both the source and the target node are not defined by the user, the source and target VMs may end up scheduled on the same node.
Though this may be useful for some use cases it's not the desired default behavior.
With this PR changes, VMs will create with `latency-check-vm` label which indicates they belong to the latency checkup.
As long as both "source_node" and "target_node" are not specified in the checkup config, both VMs won't end up running on the same node (using a [Pod Anti Affinity](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#types-of-inter-pod-affinity-and-anti-affinity) rule and the `latency-check-vm` label as the `labelSelector`).
In order to override this behavior and force both VMs to run on the same node, specify both …
> kubevirt-vm-latency: Ensure VMs are not scheduled on the same node by default

- checkups/kubevirt-vm-latency/vmlatency/internal/launcher/launcher_test.go
assert.Equal() expects the expected results to be the first argument, and the actual argument second.
Fix a call which was in the reverse order.
> vmlatency, launcher, tests: Fix a call to assert.Equal()

- checkups/kubevirt-vm-latency/vmlatency/internal/config/config_test.go
Refactor VM latency's config tests, in order to improve code readability and enable simpler addition of tests in the future.
> vmlatency, config, tests: refactor

- kiagnose/internal/checkup/checkup.go
Change the structure of checkup.go:
1. Main constructor function.
2. Checkup's methods
3. Helper constructors.
4. Helper functions.
> checkup: Re-order the functions

- automation/e2e.sh
Print the versions of `kind` and `kubectl` after installing them.
> automation, e2e: Print kind and kubectl versions

- checkups/kubevirt-vm-latency/vmlatency/internal/config/config.go
- checkups/kubevirt-vm-latency/vmlatency/internal/config/config_test.go
Currently, it is not trivial to consume a new field in the API between the framework and the checkup due to the complexity of `config.New()`:
1. Currently, there is a distinction between the states where a mandatory environment variable is:
- Missing
- Invalid
In order to reduce the number of possible emitted errors by a factor of two, and to simplify the parsing code - treat all missing mandatory environment variables as invalid.
2. Simplify the parsing and validation of the checkup's configuration:
- Read all string environment variables in one go.
- Parse all string environment variables in one go.
- Replace multiple errors related to source and target nodes with one error.
Keep the parsing and validation of integer fields as-is.
> vmlatency, config: Refactor

- checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
- checkups/kubevirt-vm-latency/vmlatency/internal/vmi/spec.go
Simplify the latency check VMI creation function [1] by moving the logic of some of the VMI spec configurations to the `vmi` package.
Also, moving the network name const closer to where it is used ([1] function).
[1]  https://github.com/kiagnose/kiagnose/blob/c8bb5e066d1b50025e1741097b6b7a697e5487f9/checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go#L122
> kubevirt-vm-latency: Simplify latency check VMI create function

- kiagnose/internal/checkup/checkup.go
- kiagnose/internal/checkup/checkup_test.go
- kiagnose/internal/checkup/job/job.go
- kiagnose/internal/launcher/launcher.go
- kiagnose/internal/launcher/launcher_test.go
- manifests/kiagnose.yaml
Currently checkup job's logs are not collected by kiagnose. 
This PR collects the checkup's logs and print them in kiagnose's logs in order to make them more visible for de facto debugging.
> checkup, Collect logs

- checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
- checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup_test.go
- checkups/kubevirt-vm-latency/vmlatency/internal/config/config.go
- checkups/kubevirt-vm-latency/vmlatency/internal/config/config_test.go
- checkups/kubevirt-vm-latency/vmlatency/internal/launcher/launcher_test.go
- checkups/kubevirt-vm-latency/vmlatency/mainflow.go
- docs/checkup_api.md
- kiagnose/internal/checkup/checkup.go
- kiagnose/internal/checkup/checkup_test.go
- kiagnose/internal/config/config.go
- kiagnose/internal/config/config_test.go
Currently, the source and target VMIs have a label `latency-check-vm` with a hard-coded empty string value.
This prevents execution of multiple instances of this checkup in parallel (for more details see issue #164).
1. Add a new `CHECKUP_UID` environment variable in the API between the framework and the checkup.
2. Change the label name to "latency-check/uid" to better reflect its value.
3. Add the checkup's UID as the value of the "latency-check/uid" label.
To get checkup's UID:
```bash
kubectl get cm -n <target-namespace> <cm-name> -o jsonpath='{.metadata.uid}'
```
To list VMI objects by checkup's UID:
```bash
kubectl get vmis -n <target-namespace> -l latency-check-vm=<checkup-UID>
```
~~Depends on PR #169.~~
Replaces PR #171.
> vmlatency: Use checkup UID as label value

- README.install.md
- README.md
- automation/e2e.sh
- checkups/echo/README.md
- checkups/echo/automation/e2e.sh
- checkups/kubevirt-vm-latency/README.md
- checkups/kubevirt-vm-latency/automation/e2e.sh
- kiagnose/internal/checkup/checkup.go
- manifests/kiagnose.yaml
In order to make checkups executable by a namespace admin, in a target namespace, while keeping the kiagnose API, 
move the kiagnose Job and RBAC objects to the target namespace.
> Deploy Kiagnose to a target namespace

- .github/workflows/check.yaml
- .github/workflows/checkup-echo.check.yaml
- .github/workflows/checkup-kubevirt-vm-latency.check.yaml
Currently, our GitHub actions checks workflows (unit tests and e2e), are triggered only on `push` or `pull_request` to the main branch. They are not triggered on stable release branches.
Add a trigger to check workflows on `push` or `pull_request` to release branches, in order to support back-porting as well.
> GitHub actions: Run checks on release branches

- checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
- checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup_test.go
- checkups/kubevirt-vm-latency/vmlatency/internal/launcher/launcher.go
- checkups/kubevirt-vm-latency/vmlatency/internal/launcher/launcher_test.go
The preflight step, in which some validation was planned to be executed, is not being used.
One of the main reasons has to do with the realization that the validations would have required elevated permissions in the cluster/NS. Moreover, such checks may just be raceful due to the K8s operation mode (e.g. the existence of an entity may say nothing about its actual state 1msec later).
Therefore, this step is removed from the checkup.
> checkups, vm-latency: Drop unused preflight step

- checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
- checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup_test.go
- checkups/kubevirt-vm-latency/vmlatency/internal/launcher/launcher.go
- checkups/kubevirt-vm-latency/vmlatency/internal/launcher/launcher_test.go
Backport #184 to stable branch release 0.2.
The preflight step, in which some validation was planned to be executed, is not being used.
One of the main reasons has to do with the realization that the validations would have required elevated permissions in the cluster/NS. Moreover, such checks may just be raceful due to the K8s operation mode (e.g. the existence of an entity may say nothing about its actual state 1msec later).
Therefore, this step is removed from the checkup.
> [release-0.2] checkups, vm-latency: Drop unused preflight step

- docs/design-proposals/kiagnose-per-namespace.md
Reduce permissions for Kiagnose deployment and execution to a namespace-admin (instead of a cluster-admin).
> design: Deploy & run kiagnose checkups in target namespace

- checkups/kubevirt-vm-latency/README.md
- checkups/kubevirt-vm-latency/automation/e2e.sh
Currently, when executing this checkup on DS, the following warning message appears:
```
Warning: would violate PodSecurity "restricted:latest":
allowPrivilegeEscalation != false (container "vm-latency-checkup"
must set securityContext.allowPrivilegeEscalation=false),
unrestricted capabilities
(container "vm-latency-checkup" must set securityContext.capabilities.drop=["ALL"]),
runAsNonRoot != true
(pod or container "vm-latency-checkup" must set securityContext.runAsNonRoot=true),
seccompProfile
(pod or container "vm-latency-checkup" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
```
Add a [securityContext](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#securitycontext-v1-core) to the checkup's container.
Signed-off-by: Orel Misan …
> vmlatency: Add securityContext to checkup's container

- checkups/kubevirt-vm-latency/Dockerfile
In order to address security issues discovered in the base image, upgrade it to version `8.6-994`.
> vmlatency, Dockerfile: Upgrade base image version

- checkups/kubevirt-vm-latency/vendor/k8s.io/apimachinery/pkg/util/rand/rand.go
- checkups/kubevirt-vm-latency/vendor/modules.txt
- checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
- checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup_test.go
Currently, source and target VMI names are hard-codded. This prevents simultaneous execution of multiple checkup instances in the same namespace.
VMIs names will have a random string prefix:
`latency-check-source-<random string>`
`latency-check-target-<random string>`
Partially solves issue #164.
~~Depends on PR #205.~~
> vmlatency: Randomize VMI names

- checkups/kubevirt-vm-latency/automation/e2e.sh
Pushing the checkup image to cluster nodes local registry is done with Kind docker specific command:
`kind load docker-image ...`
Use `image-archive` instead to enable using podman.
> vmlatency, e2e: Enable using podman

- checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
- checkups/kubevirt-vm-latency/vmlatency/internal/vmi/spec.go
Currently its not possible to run multiple instances of the checkup simultaneously, one of the reasons is due to hard-coded IP and MAC addresses.
VMs from one checkup instance conflict with VMs from  another checkup instance
and may cause false checkup results.
Randomize the MAC and IP addresses in order prevent such conflicts.
Fixes https://github.com/kiagnose/kiagnose/issues/164
> vmlatency: Randomize VMs MAC and IP addresses

- checkups/kubevirt-vm-latency/vmlatency/internal/launcher/launcher_test.go
Currently, the launcher tests uses the "default" namespace. In order to better showcase the checkup usage, use the "target-ns" instead.
> vmlatency, launcher, tests: Use target namespace

- checkups/kubevirt-vm-latency/go.sum
Following #213, it seems that vmlatency models are not "tidy", this PR updated the relevant dependencies.
> vmlatency: Deps update

- checkups/kubevirt-vm-latency/Dockerfile
- checkups/kubevirt-vm-latency/README.md
- checkups/kubevirt-vm-latency/automation/e2e.sh
Currently, the vm latency Dockerfile does not specify the user running the kubevirt-vm-latency, thus it is implicitly running as root.
This required the checkup Job to specify the container's user.
Add a `USER` stanza to the vm latency checkup's Dockerfile.
Remove `runAsUser` from the container's securityContext.
Install `shadow-utils` in the image in order to use the `adduser` command, and remove it after creating the user.
> vmlatency: Define user at Dockerfile

- checkups/kubevirt-vm-latency/vendor/github.com/kiagnose/kiagnose/kiagnose/configmap/configmap.go
- kiagnose/configmap/configmap.go
Remove unused functions `Create()` and `Delete()`.
These functions are leftovers from before PR #189.
> configmap: Remove unused functions

- checkups/kubevirt-vm-latency/vmlatency/internal/config/config.go
- checkups/kubevirt-vm-latency/vmlatency/internal/config/config_test.go
Since PR #189, the checkup receives its parameters from the user-supplied ConfigMap instead from environment variables.
Change the terminology of environment variables to params in order to reflect the new status.
Note: This changes error messages seen by the user.
> vmlatency, config: Change environment to params

- checkups/kubevirt-vm-latency/vendor/github.com/kiagnose/kiagnose/kiagnose/config/config.go
- checkups/kubevirt-vm-latency/vmlatency/internal/config/config.go
- checkups/kubevirt-vm-latency/vmlatency/mainflow.go
- kiagnose/config/config.go
- kiagnose/config/config_test.go
Since PR https://github.com/kiagnose/kiagnose/pull/189, the checkup receives its parameters
from the user-supplied ConfigMap instead from environment variables.
Currently, the read params are converted to type EnvVar, and then back to map[string]string.
Remove these redundant conversions.
Remove some dependencies as a side effect.
Note: This change breaks the current interface provided by the kiagnose library.
~~Depends on PR #219.~~
> config: Remove conversion to EnvVars and back

- checkups/kubevirt-vm-latency/vendor/github.com/kiagnose/kiagnose/kiagnose/config/config.go
- kiagnose/config/config.go
- kiagnose/config/config_test.go
Currently, the `ReadFromConfigMap()` function returns a pointer to `config.Config{}` struct.
This struct should be read-only, and has no mutating methods, so there is no need to return a pointer to it.
Note: This change breaks the API between the kiagnose library and the VM latency checkup.
> config: Change ReadFromConfigMap() returned value

- checkups/kubevirt-vm-latency/vmlatency/internal/config/config.go
- checkups/kubevirt-vm-latency/vmlatency/internal/config/config_test.go
- checkups/kubevirt-vm-latency/vmlatency/mainflow.go
Currently, the checkup's `config.Config{}` struct is built from a subset of the base config originating from the library's `config.Config{}` struct (its Params field).
Build the checkup's config from the base config in order to prepare for additional common fields which will originate from the kiagnose library.
> vmlatency, config: Build checkup config from base config

- checkups/kubevirt-vm-latency/README.md
- checkups/kubevirt-vm-latency/automation/e2e.sh
- checkups/kubevirt-vm-latency/vendor/github.com/kiagnose/kiagnose/kiagnose/config/config.go
- checkups/kubevirt-vm-latency/vendor/github.com/kiagnose/kiagnose/kiagnose/config/environment.go
- checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
- checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup_test.go
- checkups/kubevirt-vm-latency/vmlatency/internal/config/config.go
- checkups/kubevirt-vm-latency/vmlatency/internal/config/config_test.go
- checkups/kubevirt-vm-latency/vmlatency/internal/vmi/spec.go
- kiagnose/config/config.go
- kiagnose/config/config_test.go
- kiagnose/config/environment.go
Currently, if a problem occurs during the teardown process, one or more VMIs could stay in the namespace as leftovers.
Add OwnerReference to source and target VMIs, in order to use the automatic K8s garbage collector, so they will be
garbage-collected when the checkup Pod is deleted.
The ownerReference is only created if the Pod's name and UID are known: The name should always be present, the UID is dependent on the user's configuration of downward API.
> vmlatency, checkup: Add OwnerReference to VMIs

- checkups/kubevirt-vm-latency/cmd/main.go
Currently, the second `err` variable is shadowing the first. Use a single `err` variable instead of two.
> vmlatency, main: Fix variable shadowing

- checkups/kubevirt-vm-latency/Dockerfile
Currently, the Dockerfile is using the `CMD` stanza, which is supposed to provide defaults for an executing container [1].
Use the `ENTRYPOINT` stanza instead, which is used to configure a container that will run as an executable [2].
[1] https://docs.docker.com/engine/reference/builder/#cmd 
[2] https://docs.docker.com/engine/reference/builder/#entrypoint
> vmlatency, Dockerfile: Use Entrypoint instead of CMD

- .github/workflows/checkup-kubevirt-vm-latency.check.yaml
- automation/e2e.sh
- checkups/kubevirt-vm-latency/automation/e2e.sh
- test/README.md
- test/e2e/__init__.py
- test/e2e/conftest.py
- test/e2e/role.py
- test/e2e/vmlatency/__init__.py
- test/e2e/vmlatency/conftest.py
- test/e2e/vmlatency/job.py
- test/e2e/vmlatency/vmi.py
- test/e2e/vmlatency/vmlatency_test.py
- test/infra/Dockerfile
- test/infra/requirements.txt
Introduce an E2E test suite, based on the pytest testing framework.
The tests mimics the existing `kubevirt-vm-latency` checkup e2e test which is implemented in a `bash` script.
Following changes are planned to include:
- Remove the `bash` e2e tests.
- Push the test-image to the registry and auto-build it per need (when the Dockerfile or the requirements.txt files change).
> Introduce python based e2e tests

- checkups/kubevirt-vm-latency/README.md
- checkups/kubevirt-vm-latency/automation/e2e.sh
- checkups/kubevirt-vm-latency/vmlatency/internal/config/config.go
- checkups/kubevirt-vm-latency/vmlatency/internal/config/config_test.go
Currently, the status fields and params fields are in different formats, params fields are snake case and the status fields are camel case.
Change the params fields to be aligned with status fields camel case format, its common format in k8s eco-system.
The current changes do not remove the old form parameters completely and they **can** be used.
The old form parameters should be removed when deprecated completely.
> vmlatency:  Align 'spec' and 'status' field names format 

- checkups/kubevirt-vm-latency/README.md
Following PR https://github.com/kiagnose/kiagnose/pull/219, we now treat our inputs as parameters
and not as environment variables.
Update the error message accordingly.
> vmlatency, README: Update section about invalid params

- test/e2e/vmlatency/vmlatency_test.py
Following #228, update the e2e tests to use the new parameters form.
> vmlatnecy, e2e: Use parameters new form

- checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
- checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup_test.go
- checkups/kubevirt-vm-latency/vmlatency/internal/client/client.go
- checkups/kubevirt-vm-latency/vmlatency/internal/launcher/launcher_test.go
- checkups/kubevirt-vm-latency/vmlatency/internal/vmi/operation.go
Currently, functions from the client layer does not accept a context as a parameter, thus making them un-cancelable from the outside.
Add a context parameter to applicable functions from the client layer, in order to be able to cancel them from the outside.
This will be used in a follow-up PR to enforce the timeout parameter specified by the user.
> vmlatency, client: Add context to client layer

- checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
- checkups/kubevirt-vm-latency/vmlatency/internal/launcher/launcher.go
- checkups/kubevirt-vm-latency/vmlatency/internal/launcher/launcher_test.go
- checkups/kubevirt-vm-latency/vmlatency/internal/vmi/operation.go
- checkups/kubevirt-vm-latency/vmlatency/mainflow.go
Currently, the user-supplied `timeout` field is not respected.
Create a context with timeout based on the user-supplied `timeout` field, and pass it along to the checkup's `Setup()` method.
Follow-up PR(s) will pass this context to the `Run()` and `Teardown()` methods, and include e2e tests for the completed feature.
~~Depends on PR #230.~~
> vmlatency: Partially respect the user-supplied timeout

- checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
- checkups/kubevirt-vm-latency/vmlatency/internal/launcher/launcher.go
- checkups/kubevirt-vm-latency/vmlatency/internal/vmi/operation.go
This is a follow-up to PR #234.
Pass the context with timeout based on the user-supplied timeout field, to the checkup's `Teardown()` method.
~~Depends on PR #234.~~
> vmlatency: Respect the user-supplied timeout in teardown

- test/e2e/vmlatency/job.py
The e2e tests have been running with the wrong image (the one from main) instead of the one build from the source-code.
> tests, e2e: Fix the checkup image tag

- checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go
- checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup_test.go
- checkups/kubevirt-vm-latency/vmlatency/internal/config/config.go
- checkups/kubevirt-vm-latency/vmlatency/internal/config/config_test.go
- checkups/kubevirt-vm-latency/vmlatency/internal/latency/pingparser.go
Currently, if the actual measured latency is less than 1ms, it is considered as 0ms.
This created a small bug[1] when the max desired latency was 0ms.
Improve the comparison of the max desired latency and the actual measured latency.
[1] https://bugzilla.redhat.com/show_bug.cgi?id=2156392
> vmlatency: Fix latency comparison

- checkups/kubevirt-vm-latency/Dockerfile
In order to address security issues discovered in the current base image, and to get the latest ubi image, update the base image to ubi-minimal 9[1].
Also add `-y` flags to microdnf commands, so they will not hang.
[1] https://catalog.redhat.com/software/containers/ubi9/ubi-minimal/615bd9b4075b022acc111bf5
> vmlatency, Dockerfile: Update base image to ubi-minimal9

- .github/workflows/checkup-kubevirt-vm-latency.check.yaml
Currently, the e2e tests are failing on `ubuntu-latest` (Ubuntu-22.04).
Execute the e2e tests on `ubuntu-20.04`.
https://github.blog/changelog/2022-11-09-github-actions-ubuntu-latest-workflows-will-use-ubuntu-22-04/
> [release-0.2] e2e: Execute on Ubuntu 20.04

- checkups/kubevirt-vm-latency/Dockerfile
Bump the base image to:
`registry.access.redhat.com/ubi9/ubi-minimal:9.3-1475`
which is the current latest.
> VM Latency: Bump base image

- checkups/kubevirt-vm-latency/vmlatency/internal/latency/latency.go
- checkups/kubevirt-vm-latency/vmlatency/internal/latency/pingparser.go
- checkups/kubevirt-vm-latency/vmlatency/internal/latency/pingparser_test.go
Currently, there is the following warning message in the
checkup's log:
```
ping parser: failed to parse 'time': time: invalid duration "ms"
```
This is caused because the checkup uses a ping
utility that does not produce the actual duration
which is expected by `ParsePingResults`.
Simplify the `ParsePingResults`:
1. The statistics pattern is unified and simplified.
2. The matching logic is simplified.
Error handling is added.
The packet loss percentage is not parsed, since it is
not part of the `Results` struct.
Fixes [CNV-34488](https://issues.redhat.com/browse/CNV-34488).
> VMLatency: Fix ping parser warning message

- checkups/kubevirt-vm-latency/Dockerfile
Bump the base image version to `9.4-949`.
> VMLatency: Bump base image

- checkups/kubevirt-vm-latency/go.mod
- checkups/kubevirt-vm-latency/go.sum
- checkups/kubevirt-vm-latency/vendor/modules.txt
trivy [1] indicates that the checkup uses a vulnerable version of grpc [2].
Bump to a version without known vulnerabilities.
[1] https://github.com/aquasecurity/trivy
[2] GHSA-xr7q-jx4m-x55m
> VM Latency: Bump google.golang.org/grpc
