kiagnose/kiagnose

go.mod, go.sum, kiagnose/mainflow.go, kiagnose/mainflow_test.go, vendor/github.com/stretchr/testify/assert/assertion_compare.go, vendor/github.com/stretchr/testify/assert/assertion_compare_can_convert.go, vendor/github.com/stretchr/testify/assert/assertion_compare_legacy.go, vendor/github.com/stretchr/testify/assert/assertion_format.go, vendor/github.com/stretchr/testify/assert/assertion_forward.go, vendor/github.com/stretchr/testify/assert/assertion_order.go, vendor/github.com/stretchr/testify/assert/assertions.go, vendor/github.com/stretchr/testify/require/require.go, vendor/github.com/stretchr/testify/require/require_forward.go, vendor/modules.txt
Introduce kiagnose mainflow skeleton for launching and managing
checkups lifecycle (e.g: setup, teardown, result reporting).
=> Introduce mainflow skeleton 

.github/workflows/check.yaml
=> Use arnested/go-version-action

.github/workflows/check.yaml, .gitignore, automation/make.sh, kiagnose/cmd/environment.go, kiagnose/cmd/main.go
This adds a main function to kiagnose.
This is a required step in order to build an image.
=> cmd: Add main function

.github/workflows/publish.yaml, automation/make.sh
After PRs are merged the echo image has to be builded and pushed to quay
for users to consume it.
=> automation: Push echo image to quay at main push

kiagnose/internal/launcher/launcher.go, kiagnose/internal/reporter/reporter.go, kiagnose/internal/reporter/reporter_test.go, kiagnose/internal/status/status.go
=> launcher: refactor exit points

checkups/kubevirt-vm-latency/automation/e2e.sh
Add a target to the e2e script that deploys CNAO with multus and bridge
CNI/s.
=> checkups, vm-latency, automation: Deploy CNAO

checkups/kubevirt-vm-latency/automation/e2e.sh
Define a NetworkAttachementDefinition that uses a bridge CNI.
Depends on #69
=> checkups, vm-latency, automation: Define NAD (bridge)

kiagnose/internal/checkup/checkup.go
=> kiagnose, checkup: Format the code

automation/e2e.sh, automation/make.sh
This PR is fixing some shellcheck issues on the automation scripts.
=> Add shellcheck fixes

checkups/kubevirt-vm-latency/automation/e2e.sh
Add a `--clean-run` target to vm latency checkup `e2e.sh` script.
The target removes the user-supplied Job and ConfigMap objects.
=> latency, e2e: Add clean-run target

kiagnose/internal/checkup/checkup_test.go
=> checkup, tests: Fix typo at assertResultsConfigMapCreated()

README.install.md, README.md
=> README: Add initial usage instructions

README.md
=> README, Checkup Results Retrieval: Remove duplication

README.release.md
=> readme: Introduce a release instruction document

kiagnose/internal/checkup/checkup.go, kiagnose/internal/checkup/checkup_test.go
Currently, the checkup ServiceAccount object's name is constant.
As a preliminary step to checkup execution in a target namespace,
name the checkup ServiceAccount with the following format:
`<user-supplied-CM-name>-sa`
~~Depends on PR #128.~~
=> checkup: Name checkup SA after user-supplied CM

kiagnose/internal/checkup/checkup_test.go
Currently, `TestCheckupTeardownShould()` has several subtests.
It is long and difficult to change.
Split each subtest of `TestCheckupTeardownShould()` to a new test.
=> checkup, tests: Split TestCheckupTeardownShould()

docs/design-proposals/execute_checkup_in_existing_ns.md
=> docs: Add design proposal to exec checkups in existing ns

checkups/kubevirt-vm-latency/vmlatency/internal/reporter/reporter_test.go
This PR enhances the reporter unit tests to also check conversion of values set on the results configmap
=> vm-latency, reporter: Enhance results tests

checkups/kubevirt-vm-latency/README.md
Following PR #157, update the fields that were added to the checkup's results:
- status.result.sourceNode
- status.result.targetNode
=> vmlatency: Update README

automation/e2e.sh
Following #152, this is a small fix that makes `--create-multi-node-cluster` configure the network only when the cluster is created.
=> automation, e2e: Configure nodes network only on cluster creation

checkups/echo/Dockerfile, checkups/kubevirt-vm-latency/Dockerfile, dockerfiles/Dockerfile.kiagnose
Bump base image version of:
- Kiagnose
- Echo checkup
- VM latency checkup
=> Bump Base image version

.github/workflows/check.yaml, .github/workflows/checkup-echo.check.yaml, .github/workflows/checkup-kubevirt-vm-latency.check.yaml
This is a backport of PR #186 to release-0.2 branch.
=> [release-0.2] GitHub actions: Run checks on release branches

README.install.md, README.md, automation/e2e.sh, checkups/echo/README.md, checkups/echo/automation/e2e.sh, checkups/kubevirt-vm-latency/README.md, checkups/kubevirt-vm-latency/automation/e2e.sh, kiagnose/internal/checkup/checkup.go, manifests/kiagnose.yaml
This is a backport of PR #182 to release-0.2 branch.
=> [release-0.2] Deploy Kiagnose to a target namespace

CHANGELOG
=> [Release 0.2.1] Update CHANGELOG

checkups/kubevirt-vm-latency/README.md, manifests/kiagnose-configmap-access.yaml
Changed the role kiagnose-configmap-access.
=> Refactor permissions yaml into a single line array

checkups/kubevirt-vm-latency/vmlatency/internal/config/config.go
=> vmlatency, config: Reduce deprecation comments

checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup.go, checkups/kubevirt-vm-latency/vmlatency/internal/checkup/checkup_test.go, test/e2e/vmlatency/vmlatency_test.py
In scenarios where the setup step fails, the teardown step will not be triggered.
The setup should handle its own cleanup, i.e. deleting the VMI/s created as a best effort attempt.
~~Depends on #240~~
=> vmlatency, checkup, setup: Delete VMI/s if setup fails
